// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlqdNu3uT-gE8PvAgzizUwmnJYwHVQaw',
    appId: '1:112967458995:android:8bb2d801b4eb66d23310c6',
    messagingSenderId: '112967458995',
    projectId: 'whatsapp-clone-83cd4',
    databaseURL: 'https://whatsapp-clone-83cd4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsapp-clone-83cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYq4ouMlOBneEfwjUHUAdjcnXWLp_HcFo',
    appId: '1:112967458995:ios:d703479633fbc8fd3310c6',
    messagingSenderId: '112967458995',
    projectId: 'whatsapp-clone-83cd4',
    databaseURL: 'https://whatsapp-clone-83cd4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsapp-clone-83cd4.appspot.com',
    androidClientId: '112967458995-r1o2qb0q7cobtpgi75vntv93hiue2rrq.apps.googleusercontent.com',
    iosClientId: '112967458995-qu7geq7hfdhu9db0frq7g8t0d7a4t4pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappclone',
  );
}
